import { describe, expect, test } from 'bun:test';
import * as XLSX from 'xlsx';

import {
  convertTabularFile,
  convertTabularFiles,
  escapeMarkdownCell,
  HOTEL_SCHEMAS
} from './tabular.js';

const pmsHeaders = HOTEL_SCHEMAS.find((schema) => schema.id === 'pms-daily-export').columns;

describe('tabular upload conversion', () => {
  test('converts quoted CSV data into an escaped Markdown file', async () => {
    const csv = [
      pmsHeaders.join(','),
      '2026-07-11,ACR,213,196,41160,210,0.92,OTA,"Brand,\nDirect",KR,21,3,0.89,205,0.87,198,180',
      '2026-07-12,AMN,127,101,15453,153,0.80,Direct,"Partner | Desk",VN,14,1,0.82,155,0.75,149,95'
    ].join('\n');
    const result = await convertTabularFile(new File([csv], 'daily export.csv', { type: 'text/csv' }));

    expect(result.ok).toBe(true);
    expect(result.rowCount).toBe(2);
    expect(result.filename).toBe('daily_export.md');
    expect(result.markdown).toContain('Brand,<br>Direct');
    expect(result.markdown).toContain('Partner \\| Desk');
    expect(result.markdownFile.type).toStartWith('text/markdown');
  });

  test('reads every XLSX sheet and selects the sheet matching the hotel schema', async () => {
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(
      workbook,
      XLSX.utils.aoa_to_sheet([['note'], ['Generated by PMS']]),
      'Notes'
    );
    XLSX.utils.book_append_sheet(
      workbook,
      XLSX.utils.aoa_to_sheet([
        pmsHeaders,
        ['2026-07-11', 'ACR', 213, 196, 41160, 210, 0.92, 'OTA', 'Booking.com', 'KR', 21, 3, 0.89, 205, 0.87, 198, 180]
      ]),
      'Daily Data'
    );
    const bytes = XLSX.write(workbook, { type: 'array', bookType: 'xlsx' });
    const result = await convertTabularFile(
      new File([bytes], 'anam workbook.xlsx', {
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
      })
    );

    expect(result.ok).toBe(true);
    expect(result.sheetCount).toBe(2);
    expect(result.primarySheet.name).toBe('Daily Data');
    expect(result.markdown).toContain('## Notes');
    expect(result.markdown).toContain('## Daily Data');
  });

  test('accepts the repository canonical performance export', async () => {
    const sample = Bun.file('../data/sample/the_anam_daily_reservation_performance.csv');
    const result = await convertTabularFile(
      new File([await sample.arrayBuffer()], 'the_anam_daily_reservation_performance.csv')
    );

    expect(result.ok).toBe(true);
    expect(result.matchedSchema.id).toBe('canonical-performance');
    expect(result.rowCount).toBeGreaterThan(1000);
  });

  test('accepts every repository hotel dataset schema', async () => {
    const fixtures = [
      ['the_anam_properties.csv', 'property-reference'],
      ['the_anam_rooms.csv', 'room-inventory'],
      ['the_anam_daily_guest_flow.csv', 'daily-guest-flow']
    ];

    for (const [filename, schemaId] of fixtures) {
      const sample = Bun.file(`../data/sample/${filename}`);
      const result = await convertTabularFile(new File([await sample.arrayBuffer()], filename));
      expect(result.ok).toBe(true);
      expect(result.matchedSchema.id).toBe(schemaId);
    }
  });

  test('recognizes and passes through a Markdown hotel table', async () => {
    const result = await convertTabularFile(
      new File(
        [
          [
            '# Existing export',
            '',
            '| property | city | province | country | property_type | room_count | currency | timezone |',
            '| --- | --- | --- | --- | --- | --- | --- | --- |',
            '| ACR | Cam Ranh | Khanh Hoa | Vietnam | Resort | 213 | VND | Asia/Ho_Chi_Minh |'
          ].join('\n')
        ],
        'properties.md'
      )
    );

    expect(result.ok).toBe(true);
    expect(result.filename).toBe('properties.md');
    expect(result.matchedSchema.id).toBe('property-reference');
    expect(result.markdown).toContain('| ACR |');
  });

  test('rejects Markdown without a recognized hotel table', async () => {
    const result = await convertTabularFile(
      new File(['# Notes\n\nThis is not a hotel data export.'], 'notes.md')
    );

    expect(result.ok).toBe(false);
    expect(result.error).toContain('supported hotel data schema');
  });

  test('allows a recognized Markdown performance export as the primary dataset', async () => {
    const divider = pmsHeaders.map(() => '---');
    const row = [
      '2026-07-11', 'ACR', '213', '196', '41160', '210', '0.92', 'OTA',
      'Booking.com', 'KR', '21', '3', '0.89', '205', '0.87', '198', '180'
    ];
    const markdown = [
      `| ${pmsHeaders.join(' | ')} |`,
      `| ${divider.join(' | ')} |`,
      `| ${row.join(' | ')} |`
    ].join('\n');
    const result = await convertTabularFiles([new File([markdown], 'daily.md')]);

    expect(result.ok).toBe(true);
    expect(result.matchedSchema.id).toBe('pms-daily-export');
    expect(result.markdownFiles[0].name).toBe('daily.md');
  });

  test('converts a complete multi-file hotel bundle and requires performance data', async () => {
    const fixtureNames = [
      'the_anam_daily_reservation_performance.csv',
      'the_anam_properties.csv',
      'the_anam_rooms.csv',
      'the_anam_daily_guest_flow.csv'
    ];
    const files = await Promise.all(
      fixtureNames.map(async (filename) => {
        const sample = Bun.file(`../data/sample/${filename}`);
        return new File([await sample.arrayBuffer()], filename);
      })
    );
    const result = await convertTabularFiles(files);

    expect(result.ok).toBe(true);
    expect(result.markdownFiles).toHaveLength(4);
    expect(result.matchedSchemas.map((schema) => schema.id).sort()).toEqual([
      'canonical-performance',
      'daily-guest-flow',
      'property-reference',
      'room-inventory'
    ]);

    await expect(convertTabularFiles(files.slice(1))).rejects.toThrow(
      'Include at least one daily reservation/performance dataset'
    );
  });

  test('rejects unsupported and empty files', async () => {
    await expect(convertTabularFile(new File(['value'], 'daily.txt'))).rejects.toThrow(
      'Choose a CSV, XLSX, or Markdown file.'
    );
    await expect(convertTabularFile(new File([], 'daily.csv'))).rejects.toThrow(
      'The selected file is empty.'
    );
  });

  test('escapes Markdown control characters and line breaks', () => {
    expect(escapeMarkdownCell('a\\b|c\nnext')).toBe('a\\\\b\\|c<br>next');
  });
});
